// <auto-generated />
namespace GeoTurk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initdatabase005 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initdatabase005));
        
        string IMigrationMetadata.Id
        {
            get { return "201705121859346_init-database-005"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
